export {default as Routes} from './Routes'
export {default as Home} from './Home'
export {default as PageNotFound} from './PageNotFound'
export {default as Font} from './Font'
export {default as Search} from './Search'
export {default as Navbar} from './Navbar'
